### ISSUE TITLE
Blank screen when navigating to the collection tab in the admin overlay

### ISSUE THREAD

**Issue by CanOfBees** [qadan/islandora_batch_derivative_trigger#1]
Hi qadan,

Thanks for sharing this module. I'm running into a problem on 7.x-1.4, though, where navigating to the collection tab in the admin overlay results in a completely blank screen. I've test without the admin overlay and I'm getting the same behavior.

Cheers,
Bridger

**Comment by qadan** [comment]
https://github.com/qadan/islandora_generate_collection_derivatives/commit/c449e3759de60fded29b7d370425376104a48050 boo for leaving in functions that don't exist

**Comment by CanOfBees** [comment]
That's got it. Thanks again for your help.
